-- begin CLINIC_CITA
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID)^
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_ESPECIALISTA foreign key (ESPECIALISTA_ID) references CLINIC_ESPECIALISTA(ID)^
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_SERVICIO foreign key (SERVICIO_ID) references CLINIC_SERVICIO(ID)^
create index IDX_CLINIC_CITA_ON_PACIENTE on CLINIC_CITA (PACIENTE_ID)^
create index IDX_CLINIC_CITA_ON_ESPECIALISTA on CLINIC_CITA (ESPECIALISTA_ID)^
create index IDX_CLINIC_CITA_ON_SERVICIO on CLINIC_CITA (SERVICIO_ID)^
-- end CLINIC_CITA
-- begin CLINIC_EXPEDIENTE
alter table CLINIC_EXPEDIENTE add constraint FK_CLINIC_EXPEDIENTE_ON_ESPECIALISTA foreign key (ESPECIALISTA_ID) references CLINIC_ESPECIALISTA(ID)^
alter table CLINIC_EXPEDIENTE add constraint FK_CLINIC_EXPEDIENTE_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID)^
create index IDX_CLINIC_EXPEDIENTE_ON_ESPECIALISTA on CLINIC_EXPEDIENTE (ESPECIALISTA_ID)^
create index IDX_CLINIC_EXPEDIENTE_ON_PACIENTE on CLINIC_EXPEDIENTE (PACIENTE_ID)^
-- end CLINIC_EXPEDIENTE
-- begin CLINIC_ESPECIALISTA
create unique index IDX_CLINIC_ESPECIALISTA_UNIQ_DNI on CLINIC_ESPECIALISTA (DNI, DELETE_TS) ^
-- end CLINIC_ESPECIALISTA

-- begin CLINIC_DATOS_ADMINISTRATIVOS
alter table CLINIC_DATOS_ADMINISTRATIVOS add constraint FK_CLINIC_DATOS_ADMINISTRATIVOS_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID)^
alter table CLINIC_DATOS_ADMINISTRATIVOS add constraint FK_CLINIC_DATOS_ADMINISTRATIVOS_ON_RESPONSABLE_TRATAMIENTO_DATOS foreign key (RESPONSABLE_TRATAMIENTO_DATOS_ID) references CLINIC_DATOS_EMPRESA(ID)^
create unique index IDX_CLINIC_DATOS_ADMINISTRATIVOS_UNIQ_NUMERO_DOCUMENTO on CLINIC_DATOS_ADMINISTRATIVOS (NUMERO_DOCUMENTO, DELETE_TS) ^
create index IDX_CLINIC_DATOS_ADMINISTRATIVOS_ON_PACIENTE on CLINIC_DATOS_ADMINISTRATIVOS (PACIENTE_ID)^
create index IDX_CLINIC_DATOS_ADMINISTRATIVOS_ON_RESPONSABLE_TRATAMIENTO_DATOS on CLINIC_DATOS_ADMINISTRATIVOS (RESPONSABLE_TRATAMIENTO_DATOS_ID)^
-- end CLINIC_DATOS_ADMINISTRATIVOS
-- begin CLINIC_DATOS_CONTACTO
alter table CLINIC_DATOS_CONTACTO add constraint FK_CLINIC_DATOS_CONTACTO_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID)^
create index IDX_CLINIC_DATOS_CONTACTO_ON_PACIENTE on CLINIC_DATOS_CONTACTO (PACIENTE_ID)^
-- end CLINIC_DATOS_CONTACTO
-- begin CLINIC_DATOS_FACTURACION
alter table CLINIC_DATOS_FACTURACION add constraint FK_CLINIC_DATOS_FACTURACION_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID)^
create index IDX_CLINIC_DATOS_FACTURACION_ON_PACIENTE on CLINIC_DATOS_FACTURACION (PACIENTE_ID)^
-- end CLINIC_DATOS_FACTURACION
