-- begin CLINIC_CITA
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID)^
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_ESPECIALISTA foreign key (ESPECIALISTA_ID) references CLINIC_ESPECIALISTA(ID)^
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_SERVICIO foreign key (SERVICIO_ID) references CLINIC_SERVICIO(ID)^
create index IDX_CLINIC_CITA_ON_PACIENTE on CLINIC_CITA (PACIENTE_ID)^
create index IDX_CLINIC_CITA_ON_ESPECIALISTA on CLINIC_CITA (ESPECIALISTA_ID)^
create index IDX_CLINIC_CITA_ON_SERVICIO on CLINIC_CITA (SERVICIO_ID)^
-- end CLINIC_CITA
-- begin CLINIC_EXPEDIENTE
alter table CLINIC_EXPEDIENTE add constraint FK_CLINIC_EXPEDIENTE_ON_ESPECIALISTA foreign key (ESPECIALISTA_ID) references CLINIC_ESPECIALISTA(ID)^
alter table CLINIC_EXPEDIENTE add constraint FK_CLINIC_EXPEDIENTE_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID)^
create index IDX_CLINIC_EXPEDIENTE_ON_ESPECIALISTA on CLINIC_EXPEDIENTE (ESPECIALISTA_ID)^
create index IDX_CLINIC_EXPEDIENTE_ON_PACIENTE on CLINIC_EXPEDIENTE (PACIENTE_ID)^
-- end CLINIC_EXPEDIENTE
-- begin CLINIC_ESPECIALISTA
create unique index IDX_CLINIC_ESPECIALISTA_UNIQ_DNI on CLINIC_ESPECIALISTA (DNI, DELETE_TS) ^
-- end CLINIC_ESPECIALISTA
-- begin CLINIC_PACIENTE
create unique index IDX_CLINIC_PACIENTE_UNIQ_DNI on CLINIC_PACIENTE (DNI, DELETE_TS) ^
-- end CLINIC_PACIENTE
