alter table CLINIC_DATOS_FACTURACION add constraint FK_CLINIC_DATOS_FACTURACION_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID);
create index IDX_CLINIC_DATOS_FACTURACION_ON_PACIENTE on CLINIC_DATOS_FACTURACION (PACIENTE_ID);
