alter table CLINIC_DATOS_CONTACTO add constraint FK_CLINIC_DATOS_CONTACTO_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID);
create index IDX_CLINIC_DATOS_CONTACTO_ON_PACIENTE on CLINIC_DATOS_CONTACTO (PACIENTE_ID);
