alter table CLINIC_EXPEDIENTE add constraint FK_CLINIC_EXPEDIENTE_ON_ESPECIALISTA foreign key (ESPECIALISTA_ID) references CLINIC_ESPECIALISTA(ID);
alter table CLINIC_EXPEDIENTE add constraint FK_CLINIC_EXPEDIENTE_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID);
create index IDX_CLINIC_EXPEDIENTE_ON_ESPECIALISTA on CLINIC_EXPEDIENTE (ESPECIALISTA_ID);
create index IDX_CLINIC_EXPEDIENTE_ON_PACIENTE on CLINIC_EXPEDIENTE (PACIENTE_ID);
