alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_PACIENTE foreign key (PACIENTE_ID) references CLINIC_PACIENTE(ID);
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_ESPECIALISTA foreign key (ESPECIALISTA_ID) references CLINIC_ESPECIALISTA(ID);
alter table CLINIC_CITA add constraint FK_CLINIC_CITA_ON_SERVICIO foreign key (SERVICIO_ID) references CLINIC_SERVICIO(ID);
create unique index IDX_CLINIC_CITA_UNIQ_HORA on CLINIC_CITA (HORA, DELETE_TS) ;
create index IDX_CLINIC_CITA_ON_PACIENTE on CLINIC_CITA (PACIENTE_ID);
create index IDX_CLINIC_CITA_ON_ESPECIALISTA on CLINIC_CITA (ESPECIALISTA_ID);
create index IDX_CLINIC_CITA_ON_SERVICIO on CLINIC_CITA (SERVICIO_ID);
