###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.dbmsType = mssql

cuba.dbmsVersion = 2012

cuba.springContextConfig = +com/company/clinic/spring.xml

cuba.persistenceConfig = +com/company/clinic/persistence.xml

cuba.metadataConfig = +com/company/clinic/metadata.xml

cuba.viewsConfig = +com/company/clinic/views.xml

cuba.mainMessagePack = +com.company.clinic.core

cuba.keyForSecurityTokenEncryption = M2CdiUB8kTQJt4Lt

cuba.anonymousSessionId = 06983bd5-9500-0ba9-dccf-fcdcccf06a60

###############################################################################
#                                  Other                                      #
###############################################################################

cuba.webContextName = app
cuba.webPort=8080
cuba.availableLocales = English|en
cuba.localeSelectVisible = false

cuba.web.forceCleanStart=true
# Habilita la invocación local de servicios
cuba.useLocalServiceInvocation=true

# Configuración del bloque middleware
cuba.middlewareUrl=http://localhost:8080/app
cuba.middleware.connectionUrlList=http://localhost:8080/app
cuba.middleware.block=app

cuba.dataSourceProvider = application
# Local
#cuba.dataSource.jdbcUrl = jdbc:sqlserver://localhost\\SQLSERVER;databaseName=clinic
#cuba.dataSource.username = anicolcl
#cuba.dataSource.password = anicolcl
#cuba.dataSource.dbName = clinic
#cuba.dataSource.host = localhost\\SQLSERVER
#cuba.dataSource.port =
#cuba.dataSource.connectionTestQuery=select 1

# Despliegue

cuba.dataSource.jdbcUrl = jdbc:sqlserver://51.178.137.184:1433;databaseName=clinic;encrypt=true;trustServerCertificate=true;loginTimeout=30;
cuba.dataSource.username = SA
cuba.dataSource.password = Elalmendro.33

spring.data.redis.host=localhost
spring.data.redis.password=
spring.data.redis.port=6379

reporting.fontsDir = ../core/conf/fonts